### ISSUE TITLE
Add cursor pointer to labels

### ISSUE THREAD

**Issue by nicolasiensen** [basscss/base-forms#1]
By default, web developers should **always** link form labels to it's respective inputs, making labels a clickable element.

I suggest we add cursor pointer to all, or only those labels with ```for``` attribute set.

```css
label {
  cursor: pointer;
}
```
