### ISSUE TITLE
Setting hard height declaration on <input> tags is overly specific

### ISSUE THREAD

**Issue by clintonhalpin** [basscss/base-forms#3]
Hey, Hey!

I'm curious why base-forms set's a hard height declaration on inputs?

At a quick glance it seems like you could achieve a similar effect only using padding, without having to write something like the below.

```css
input[type=date], 
input[type=datetime-local], 
input[type=datetime], 
input[type=email], 
input[type=month], 
input[type=number], 
input[type=password], 
input[type=search], 
input[type=tel], 
input[type=text], 
input[type=time], 
input[type=url], 
input[type=week] {
	height: 2.75rem;
}
```
I also tried using a white-space class, which get's overridden ie.

```html
<input type="text" class="field px2 py2" />
```

=

For some color, I actually really prefer the defaults in basscss but have some specific design requirements I'm trying to workaround. So there's that :)

Thanks!

=

EDIT: ugg I just looked at issue #2 and it seems pretty much the same
